import '../mixin_challenge/mammals/dolphin.dart';
import '../mixin_challenge/mammals/bat.dart';
import '../mixin_challenge/mammals/cat.dart';
import '../mixin_challenge/bird/dove.dart';
import '../mixin_challenge/bird/duck.dart';
import '../mixin_challenge/fish/shark.dart';
import '../mixin_challenge/fish/flyingFish.dart';

void main(List<String> args) {
  Dolphin suki = Dolphin("Suki", 5);
  suki.Name();
  suki.isMammal();
  suki..swim();
  print("===================");
  Bat vancher = Bat("Vancher", 3);
  vancher.Name();
  vancher.isMammal();
  vancher.fly();
  vancher.walk();
  print("===================");
  Cat neko = Cat("Neko", 3);
  neko.Name();
  neko.isMammal();
  neko.walk();
  print("===================");
  Dove dove = Dove("Dove", 2);
  dove.Name();
  dove.isBird();
  dove.fly();
  dove.walk();
  print("===================");
  Duck welky = Duck("Welky", 1);
  welky.Name();
  welky.isBird();
  welky.walk();
  welky.swim();
  welky.fly();
  print("===================");
  Shark ellen = Shark("Ellen", 17);
  ellen.Name();
  ellen.isFish();
  ellen.swim();
  print("===================");
  Flyingfish spear = Flyingfish("Spear", 8);
  spear.Name();
  spear.isFish();
  spear.swim();
  spear.fly();
}